library("multtest")
data("golub")
library("cluster")
#Problem 1 
# Clustering analysis on the "CCND3 Cyclin D3" gene expression values of the
# Golub et al. (1999) data.
#(a) Conduct hierarchical clustering using single linkage and Ward linkage. Plot
# the cluster dendrogram for both fit. Get two clusters from each of the
# methods. Use function table () to compare the clusters with the two patient
# groups ALL/AML. Which linkage function seems to work better here?
grep("CCND3 Cyclin D3",golub.gnames[,2])
data <- data.frame(golub[1042,])
gol.fac <- factor(golub.cl,levels=0:1, labels= c("ALL","AML"))
single_link <- hclust(dist(data, method="euclidian"), method = "single")
plot(single_link, main = "Single linkage dendrogram", labels=gol.fac)
ward <- hclust(dist(data, method = "euclidian"), method = "ward.D2")
plot(ward, main = "Ward linkage dendrogram", labels=gol.fac)
single_cluster <- cutree(single_link, k=2)
table(single_cluster, gol.fac)
ward_cluster <- cutree(ward, k=2)
table(ward_cluster, gol.fac)

# From above output, we can see that the  ward method works better, as we see that cluster generated by this method
# have a more balanced distribution of the patients.

#(b)Use k-means cluster analysis to get two clusters. Use table () to compare the
# two clusters with the two patient groups ALL/AML.
data <- data.frame(golub[1042,])
gol.fac <- factor(golub.cl,levels=0:1, labels= c("ALL","AML"))
K_CCND3 <- kmeans(data, centers = 2, nstart=10)
table(K_CCND3$cluster, gol.fac)

#(c)Which clustering approach (hierarchical versus k-means) produce the best
# matches to the two diagnose groups ALL/AML?
#By comparing with patients groups, k-means clustering produces best matches to the groups ALL and AML.

#(d)Find the two cluster means from the k-means cluster analysis. Perform a
# bootstrap on the cluster means. Do the confidence intervals for the cluster
# means overlap? Which of these two-cluster means is estimated more
# accurately?
initial <-K_CCND3$centers 
n <- dim(data)[1]; nboot<-1000
boot.cl <- matrix(NA,nrow=nboot,ncol = 4)
for (i in 1:nboot){
  dat.star <- data[sample(1:n,replace=TRUE),]
  cl <- kmeans(dat.star, initial, nstart = 10)
  boot.cl[i,] <- c(cl$centers[1], cl$centers[2])
}
apply(boot.cl,2,mean)
quantile(boot.cl[,1],c(0.025, 0.975))
quantile(boot.cl[,2],c(0.025, 0.975))
quantile(boot.cl[,3],c(0.025, 0.975))
quantile(boot.cl[,4],c(0.025, 0.975))

#(E) Produce a plot of K versus SSE, for K=1, …, 30. How many clusters does
# this plot suggest?

K<-(1:30); SSE<-rep(NA,length(K))
for (k in K) {
  SSE[k]<-kmeans(data, centers=k,nstart = 10)$tot.withinss
}
plot(K, SSE, type='o', xaxt='n'); axis(1, at = K, las=2)
# the plot shows that there is 30 c


# problem_2
# Cluster analysis on part of Golub data.
#(a) Select the oncogenes and antigens from the Golub data.
cancer <- grep("oncogene", golub.gnames[,2])
cancer
anti <- grep("antigen",golub.gnames[,2])
anti

#(b) On the selected data, do clustering analysis for the genes (not for the
# patients). Using K-means and K-medoids with K=2 to cluster the genes. Use
# table () to compare the resulting two clusters with the two gene groups
# oncogenes and antigens for each of the two-clustering analysis.
data_clus<-rbind(golub[cancer,], golub[anti,])
names <-rep(c("oncogene","antigen"), c(length(cancer), length(anti)))
k_means <- kmeans(data_clus, centers = 2)
k_medoids <-pam(data_clus, k=2)
table(k_means$cluster, names)
table(k_medoids$cluster, names)

#(c) Use appropriate tests (from previous modules) to test the marginal
# independence in the two-by-two tables in (b). Which clustering method
# provides clusters related to the two gene groups?
chisq.test(table(k_means$cluster, names))
chisq.test(table(k_medoids$cluster, names))
# Two clustering method does nothing, so both of them are bad 

#(d) Plot the cluster dendrograms for this part of golub data with single linkage
# and complete linkage, using Euclidean distance.
golub_data <- golub[c(cancer, anti),]
link_single <- hclust(dist(golub_data, method = "euclidian"), method = "single")
comp_link <- hclust(dist(golub_data, method = "euclidian"), method = "complete")
par(mfrow=c(1,2))
plot(link_single, main ="Single linkage dendrogram")
plot(comp_link, main = "Complete linkage dendrogram")

# problem_3
# The ncidata (64 by 6830 matrix) contains 6830 gene expression measurements on
# 64 cancer cell lines. The cancer cell lines labels are contained in ncilabs. We do
# clustering analysis on the 64 cell lines (the rows).
# Clustering analysis on NCI60 cancer cell line microarray data (Ross et al.2000)
install.packages('ISLR')
library("ISLR")
nci.data<-NCI60$data
nci.labs<-NCI60$labs

#(a) Using k-means clustering, produce a plot of K versus SSE, for K=1,…, 30.
# How many clusters appear to be there?
K<-(1:30); SSE<-rep(NA,length(K))
for (k in K) {
  SSE[k]<-kmeans(nci.data, centers=k,nstart = 10)$tot.withinss
}
plot(K, SSE, type='o', xaxt='n'); axis(1, at = K, las=2)

#(b) Do K-medoids clustering (K=7) with 1-correlation as the dissimilarity
# measure on the data. Compare the clusters with the cell lines. Which type of
# cancer is well identified in a cluster? Which type of cancer is not grouped
# into a cluster? According to the clustering results, which types of cancer are
# most similar to ovarian cancer?
k_medoid <- pam(dist(1-cor(t(nci.data))), k=7)
k_medoid_clus <- k_medoid$cluster
table(k_medoid_clus, nci.labs)
# according to the clustering results, lung cancer is not grouped into a single cluster 


